version: '3'

tasks:
  run:
    cmds:
      - task: build
      - ./build/agents

  build:
    cmds:
      - go build -o ./build/agents ./cmd/agents/*.go
    sources:
      - cmd/agents/*.go
      - internal/**/*.go
      - go.mod
    generates:
      - build/agents
