version: '3'

tasks:
  run:
    cmds:
      - task: build
      - rm -rf data/prompts/*
      - mkdir -p data/prompts data/prompts/analysts data/prompts/researchers data/prompts/risk data/prompts/trader
      - ./build/agents

  build:
    cmds:
      - go build -o ./build/agents ./cmd/agents/*.go
    sources:
      - cmd/agents/*.go
      - internal/**/*.go
      - go.mod
    generates:
      - build/agents
